version: "3"

services:

    #############################
    # Database
    #############################
    jpdatabase:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      expose: 
        - "3306"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: jp
          MYSQL_DATABASE: jpproject
          MYSQL_PASSWORD: 10203040
    
    #############################
    # Server SSO
    #############################
    jpproject-sso:
        image: "jpproject-sso"
        build: 
          context: .
          dockerfile: sso.dockerfile
        depends_on:
            - jpdatabase
        environment: 
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_URLS: http://+:5001
            CUSTOMCONNSTR_SSOConnection: "server=jpdatabase,port=3306;database=jpproject;user=jp;password=10203040"
            ApplicationSettings:EnableExternalProviders: "false" # Because Auth url is http://jpproject-sso (modified by host to point to 127.0.0.1), then Google and Facebook reject it.
            ApplicationSettings:DatabaseType: MySql
            ApplicationSettings:DefaultUser: bruno
            ApplicationSettings:DefaultPass: Pa$$word123
            ApplicationSettings:DefaultEmail: bhdebrito@gmail.com
            ApplicationSettings:UserManagementURL: http://localhost:4400
            ApplicationSettings:IS4AdminUi: http://localhost:4300
            ApplicationSettings:ResourceServerURL: http://localhost:5002
            ApplicationSettings:ShowDefaultUserPass: "true"
            CertificateOptions:Type: Temporary

    # #############################
    # # Management API
    # #############################
    jpproject-api:
        image: jpproject-api
        build: 
          context: .
          dockerfile: api.dockerfile
        depends_on:
            - jpdatabase
        environment: 
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_URLS: http://+
            CUSTOMCONNSTR_SSOConnection: "server=jpdatabase,port=3306;database=jpproject;user=jp;password=10203040"
            ApplicationSettings:Authority: "http://jpproject-sso:5001"
            ApplicationSettings:DatabaseType: MySql

    #############################
    # User management UI
    #############################
    jpproject-users:
        image: jpproject-users
        build: 
          context: .
          dockerfile: users.dockerfile
          args: 
            ENVIRONMENT: docker

          
    #############################
    # Admin UI
    #############################
    jpproject-admin-ui:
        image: bhdebrito/jpproject-admin-ui


    reverse-proxy:
        container_name: jpproject
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - '5001:5001'
            - '5002:5002'
            - '4400:4400'
            - '4300:4300'
        depends_on:
            - 'jpproject-api'
            - 'jpproject-users'
            - 'jpproject-sso'
